// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/web-chat/Aurora.tsx": () => import("../components/mockups/web-chat/Aurora.tsx"),
  "./components/mockups/web-chat/Editorial.tsx": () => import("../components/mockups/web-chat/Editorial.tsx"),
  "./components/mockups/web-chat/Studio.tsx": () => import("../components/mockups/web-chat/Studio.tsx")
};
